version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    env_file:
      - docker/.env
    depends_on:
      - postgres
      - redis
      - mongo

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  compass:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    ports:
      - "8081:8081"

volumes:
  postgres_data:
  mongo_data:
